"""RTT-104 data report text (called by build_rtt104_dataset.py). Deterministic: no dates or times are generated here."""
import json
import os
from decimal import Decimal

ZERO = Decimal(0)


def fmt_pop(p):
    return f"{int(Decimal(p)):,}"


def report_text(cfg, raw, economies, parl, pop, disp, elig, elig2, boards, boards2, zgroups, zgroups2, ties, ties2, ev,
                wrows, cc, diffs, owid_only, n_common, checks, years, T, T2, one_dp, pop_latest):
    data_dir = os.path.dirname(os.path.dirname(raw.rstrip("/")))
    if os.path.basename(data_dir) == "source":
        data_dir = os.path.dirname(data_dir)
    L = []
    a = L.append
    name = {c: economies[c]["short_name"] for c in economies}
    in_race = sorted((c for c in economies if elig[c] and parl.get(c)), key=lambda c: name[c])
    in_race2 = sorted((c for c in economies if elig2[c] and parl.get(c)), key=lambda c: name[c])
    by = {}
    for b in boards:
        by.setdefault((b["board"], b["year"]), []).append(b)
    by2 = {}
    for b in boards2:
        by2.setdefault((b["board"], b["year"]), []).append(b)
    passed = sum(1 for v in checks.values() if v["pass"])
    pop_years = sorted({pop_latest(pop.get(c, {}))[0] for c in economies if pop.get(c)})

    a("# RTT-104 Women in Parliament: Highest vs Lowest (1997–2025) — data report (IQ-20)")
    a("")
    a("Generated by `scripts/build_rtt104_dataset.py` from the files in `data/rtt-104/source/` (deterministic; two clean "
      "rebuilds are byte-identical, `tests/rtt104/run_tests_rtt104.py`). Brief: `prompts/CODE_SESSION_IQ-20.md`, Luke's "
      "answers `prompts/CODE_SESSION_IQ-20b.md`, Cowork's note `prompts/CODE_SESSION_IQ-20c.md`. Decisions DEC-600..DEC-623.")
    a("")
    a("> **Status: data built; rights settled by Luke as an owner-accepted risk (DEC-623).** The IPU's own terms forbid "
      "commercial use of its content, while the World Bank labels this series CC BY 4.0 (section 2, both quotes kept); Luke "
      "chose to use the World Bank's licence, crediting the IPU and the World Bank, and to take the video down if the IPU "
      "objects. The block of DEC-614 is lifted. Open: questions 2–4 (section 16); nothing is designed before Luke approves "
      "it (DEC-069).")
    a("")
    a(f"**Checks: {passed}/{len(checks)} PASS.** In the race (4 million or more, population in the latest year): "
      f"**{len(in_race)} countries** with at least one figure. Every figure on a board is a World Bank WDI value "
      "(SG.GEN.PARL.ZS, producer the Inter-Parliamentary Union), shown to one decimal; order uses full precision.")
    a("")

    # 1 sources
    man = json.load(open(os.path.join(os.path.dirname(raw), "fetch_manifest.json"), encoding="utf-8"))
    a("## 1. Sources (fetched on a GitHub runner, DEC-607)")
    a("")
    a(f"Run {man['run_url']}. Files kept byte for byte in `{os.path.relpath(raw, data_dir)}/`.")
    a("")
    a("| ID | URL | Fetched (UTC) | Bytes | SHA-256 |")
    a("|---|---|---|---|---|")
    for r in man["files"]:
        a(f"| {r['id']} | {r['url']} | {r['fetched_utc']} | {r.get('bytes', '')} | `{r.get('sha256', r.get('error', ''))}` |")
    a("")
    src = json.load(open(os.path.join(raw, "wdi_source_2.json")))[1][0]
    meta = {m["id"]: m["value"] for m in json.load(open(os.path.join(raw, "wdi_metadata_SG.GEN.PARL.ZS.json")))["source"][0]
            ["concept"][0]["variable"][0]["metatype"]}
    a(f"- World Development Indicators last updated **{src['lastupdated']}** (API). Indicator: \"{meta['IndicatorName']}\". "
      f"Definition: \"{meta['Longdefinition']}\" Method: \"{meta['Statisticalconceptandmethodology'].splitlines()[0]}\"")
    a(f"- Source note: \"{meta['Source']}\"")
    a("- Web pages (terms, metadata, IPU Parline) are not kept; their SHA-256 and short excerpts are in each fetch folder's "
      "`fetch_manifest.json` and `page_excerpts/`.")
    a("")

    # 2 terms
    a("## 2. Terms of use (read at source on the runner, 10 Oct 2026; DEC-608, DEC-615, DEC-623)")
    a("")
    a("- **IPU**, https://www.ipu.org/terms-use (last update 24 April 2024): \"Use of the Inter-Parliamentary Union (IPU) "
      "websites, ipu.org, data.ipu.org and parliamentaryindicators.org, constitutes acceptance of these Terms of Use.\" … "
      "\"All content on the IPU websites or extracts thereof may be displayed, reproduced, translated or adapted for research "
      "or personal use but not for sale or for use in conjunction with commercial purposes.\" … \"The IPU’s open access policy "
      "applies to all the publications published by the IPU and is subject to the Creative Commons "
      "Attribution-NonCommercial-ShareAlike 4.0 International License.\" … \"Any IPU datasets must also be made available to "
      "the public free of charge.\" … \"Any use of datasets from data.ipu.org should be attributed as follows: "
      "“Inter-Parliamentary Union: dataset_name, month_year”\". Cowork confirmed the first two in Luke's Chrome (DEC-615).")
    a(f"- **World Bank**, WDI metadata for SG.GEN.PARL.ZS: \"License_Type\": \"{meta['License_Type']}\", \"License_URL\": "
      f"\"{meta['License_URL']}\" (Cowork saw \"License : CC BY-4.0\" on data.worldbank.org). The licence page: \"The Creative "
      "Commons Attribution 4.0 International license allows users to copy, modify and distribute data in any format for any "
      "purpose, including commercial use.\" Population SP.POP.TOTL is also CC BY-4.0 (its metadata).")
    a("- **Our World in Data** (cross-check only, never on screen): \"Most of the data on Our World in Data comes from "
      "third-party providers (such as the WHO, UN, and World Bank) and is subject to the license terms of those providers.\"")
    a("- **The conflict:** the World Bank distributes the series as CC BY 4.0; the IPU, which produces it, forbids commercial "
      "use of its websites' content. The brief's condition was met; Cowork chose \"build data, stay blocked\" for Luke "
      "(DEC-614). Under DEC-245 nobody is contacted about data. The options were (a) owner-accepted risk on the World Bank's "
      "CC BY 4.0 label or (b) shelve. **Luke chose (a) on 10 Oct 2026 (DEC-623):** the series is used under the World "
      "Bank's CC BY 4.0 licence as an owner-accepted risk; the IPU and the World Bank are credited on screen and in the "
      "description; if the IPU objects, the video is taken down (as DEC-244). Not legal advice; Isle of Man law not checked.")
    a("")

    # 3 reference date
    a("## 3. Reference date of each year's figure (DEC-609, DEC-621)")
    a("")
    note = os.path.join(data_dir, "source", "reference_date_findings.md")
    a(open(note, encoding="utf-8").read().strip() if os.path.exists(note) else "(no findings file)")
    a("")

    # 4 population rule
    a("## 4. Population rule (DEC-604, DEC-611, DEC-612)")
    a("")
    a(f"- Rule: **{fmt_pop(T)} or more** people in the latest year with a WDI population figure (latest year used: "
      f"{', '.join(str(y) for y in pop_years)}); a country is in for the whole race or not at all. Source: WDI SP.POP.TOTL "
      "(\"midyear estimates\", CC BY-4.0), file `wdi_SP.POP.TOTL_all_1997-2026.json`.")
    a(f"- In the race: **{len(in_race)}** countries with at least one figure (at 2.5 million: {len(in_race2)}). "
      "Every country stays in `series.csv` and `countries.csv` (DEC-600).")
    near = sorted((c for c in economies if pop.get(c) and parl.get(c) and
                   Decimal("0.9") * T <= Decimal(pop_latest(pop[c])[1]) <= Decimal("1.1") * T), key=lambda c: name[c])
    a(f"- **Within ±10% of {fmt_pop(T)}** ({len(near)}): " + "; ".join(
        f"{name[c]} {fmt_pop(pop_latest(pop[c])[1])} ({'in' if elig[c] else 'out'})" for c in near) + ".")
    alt = []
    for c in sorted((c for c in economies if parl.get(c)), key=lambda c: name[c]):
        yrs_in = [y for y in years if y in pop.get(c, {}) and Decimal(pop[c][y]) >= T and disp[c][y][0] is not None]
        yrs_out = [y for y in years if y in pop.get(c, {}) and Decimal(pop[c][y]) < T and disp[c][y][0] is not None]
        if elig[c] and yrs_out:
            alt.append(f"{name[c]} would be out in {span(yrs_out)}")
        if not elig[c] and yrs_in:
            alt.append(f"{name[c]} would be in for {span(yrs_in)}")
    a("- **Under the alternative rule (population in that year)**, these would enter or leave: " + ("; ".join(alt) or "none") + ".")
    on_any = {b["iso3"] for b in boards}
    alt_board = [x for x in alt if any(name[c] == x.split(" would")[0] for c in on_any)]
    a(f"  Of these, on a board at least once under the approved rule: {', '.join(x.split(' would')[0] for x in alt_board) or 'none'}.")
    a("")

    # 5 gaps
    a("## 5. Missing years (DEC-617, Claude working choice under DEC-417)")
    a("")
    carried = sorted(((c, y, disp[c][y][2]) for c in economies for y in years if disp[c][y][1] == "latest_figure"),
                     key=lambda t: (name[t[0]], t[1]))
    a("Rule: a single missing year with a figure on both sides shows the previous figure, marked \"latest figure\"; any "
      "longer gap takes the country off the board until its next figure; a missing final run goes to the closing card only "
      "with a verified reason (DEC-613). Nothing is averaged or filled otherwise.")
    a("")
    cin = [t for t in carried if elig[t[0]]]
    a(f"- Single-year gaps: {len(carried)} in all countries, {len(cin)} in the race (all in `series.csv`, shown_as "
      "latest_figure). In the race: " + ("; ".join(f"{name[c]} {y} (shows {f})" for c, y, f in cin) or "none") + ".")
    cb = [b for b in boards if b["latest_figure"] == "yes"]
    a(f"- \"Latest figure\" bars on a board at 4 m: " + ("; ".join(
        f"{b['country']} {b['year']} ({b['board']} {b['rank']}, {b['value_1dp']}% from {b['carried_from_year']})" for b in cb)
        or "none") + ".")
    longg = sorted({(c) for c in economies if elig[c] for y in years if disp[c][y][1] == "gap_off_board"}, key=lambda c: name[c])
    a(f"- Longer gaps, off the board (in the race): " + ("; ".join(
        f"{name[c]} {span([y for y in years if disp[c][y][1] == 'gap_off_board'])}" for c in longg) or "none") + ".")
    late = sorted((c for c in in_race if min(parl[c]) > years[0]), key=lambda c: name[c])
    a(f"- First figure after {years[0]} (in the race): " + ("; ".join(f"{name[c]} {min(parl[c])}" for c in late) or "none") + ".")
    a("")

    # 6 boards
    a("## 6. Boards, every year (4 million rule)")
    a("")
    a("Top = highest share; bottom = lowest share above 0% (countries at 0% are the separate group, section 9). "
      "\"*\" = latest figure carried from the year before.")
    a("")
    for y in years:
        for bd in ("top", "bottom"):
            lst = by.get((bd, y), [])
            a(f"- **{y} {bd}:** " + ", ".join(f"{b['rank']} {b['country']} {b['value_1dp']}{'*' if b['latest_figure'] == 'yes' else ''}"
                                              for b in lst))
    a("")
    a("### 2.5 million comparison (brief; 4 m is the episode's rule)")
    a("")
    diffs25 = []
    for y in years:
        for bd in ("top", "bottom"):
            s4 = [b["country"] for b in by.get((bd, y), [])]
            s2 = [b["country"] for b in by2.get((bd, y), [])]
            if s4 != s2:
                add = [c for c in s2 if c not in s4]
                diffs25.append(f"{y} {bd}: +{', '.join(add) if add else '(order only)'}")
    a(f"At 2.5 m, {len(in_race2) - len(in_race)} more countries are in the race. Boards that would differ: "
      + ("; ".join(diffs25) or "none") + ". Full boards: `data/rtt-104/boards_2_5m_comparison.csv`.")
    a("")

    # 7 events
    a("## 7. First place, entries and exits (4 m)")
    a("")
    for bd, label in (("top", "Highest"), ("bottom", "Lowest above 0%")):
        fp = [e for e in ev if e["board"] == bd and e["event"] == "first_place"]
        a(f"- **{label}, first place:** " + "; ".join(f"{e['year']} {e['country']} ({e['value']}%)" for e in fp) + ".")
    a("")
    for bd in ("top", "bottom"):
        a(f"**{bd.capitalize()} board, entries and exits by year:**")
        a("")
        for y in years[1:]:
            en = [e for e in ev if e["board"] == bd and e["year"] == y and e["event"] == "enters"]
            lv = [e for e in ev if e["board"] == bd and e["year"] == y and e["event"] == "leaves"]
            if en or lv:
                a(f"- {y}: in " + (", ".join(f"{e['country']} ({e['detail']}, {e['value']}%)" for e in en) or "-")
                  + "; out " + (", ".join(e["country"] for e in lv) or "-"))
        a("")

    # 8 story moments
    a("## 8. Candidate story moments (WDI year and figure only; all VERIFIED in the WDI file)")
    a("")
    a("Each moment is a WDI value as published. The year is the WDI year; what date it describes is question 2.")
    a("")
    for line in story_moments(economies, parl, elig, boards, years, one_dp, name):
        a(f"- {line}")
    a("")

    # 9 zero group
    a("## 9. The 0% group by year (DEC-602; design option, not built)")
    a("")
    a("| Year | Count | Countries | In the race with a value |")
    a("|---|---|---|---|")
    for y, z, n in zgroups:
        a(f"| {y} | {len(z)} | {', '.join(t[1] for t in z) or '-'} | {n} |")
    a("")
    a(f"At 2.5 m the group would be: " + "; ".join(f"{y} {len(z)}" for y, z, n in zgroups2 if len(z)) + ".")
    a("")

    # 10 ties
    a("## 10. Ties full precision does not break (ranks 1–11)")
    a("")
    a("Order inside a tie is alphabetical in `boards.csv` (DEC-618); none of these is shown as a tie on screen until Luke decides.")
    a("")
    for t in ties:
        a(f"- {t['year']} {t['board']} ranks {t['ranks']}: {t['countries']} at {one_dp(t['value'])}% ({t['effect']})")
    if not ties:
        a("- none")
    a("")

    # 11 world panel
    a("## 11. World panel (WDI aggregate WLD, all countries — not only those in the race)")
    a("")
    a("Label in the data: \"World (all countries)\". WDI's aggregation method for this series: \""
      + meta["Aggregationmethod"] + "\".")
    a("")
    a(" · ".join(f"{w['year']} {w['value_1dp']}" for w in wrows))
    a("")

    # 12 closing card
    a("## 12. Closing card (DEC-603, DEC-613): in the race, no figure in " + str(years[-1]))
    a("")
    a("| Country | Last figure | On card | Proposed line (design session) | Status | Source | Quote |")
    a("|---|---|---|---|---|---|---|")
    for r in cc:
        a(f"| {r['country']} | {r['last_figure_year']} ({r['last_figure_1dp']}%) | {r['on_card']} | {r['card_wording'] or '-'} | "
          f"{r['status']} | {r['source_url']} | {(r['quote'] or r['note']).replace('|', '/')} |")
    a("")
    out_cc = [c for c in economies if not elig[c] and parl.get(c) and years[-1] not in parl[c]]
    a("Below 4 m with no " + str(years[-1]) + " figure (not in the race, never on the card): "
      + (", ".join(sorted(name[c] for c in out_cc)) or "none") + ".")
    a("")

    # 13 WDI vs OWID
    a("## 13. World Bank WDI vs Our World in Data, cell by cell")
    a("")
    rd = [d for d in diffs if d["difference"] == "rounding"]
    vd = [d for d in diffs if d["difference"] == "value"]
    ow = [d for d in diffs if d["difference"] == "only in OWID"]
    wd = [d for d in diffs if d["difference"] == "only in WDI"]
    a(f"Compared {n_common} cells present in both. OWID prints 6 decimals: **{len(rd)}** cells differ only in the 6th or "
      f"7th decimal (\"rounding\", under 0.00001; never visible at one decimal). Real value differences: **{len(vd)}**; only "
      f"in WDI: **{len(wd)}**; only in OWID: **{len(ow)}**. OWID's copy is \"World Development Indicators 129\" (OWID "
      "lastUpdated 2026-07-27); WDI was updated 2026-10-08. Every difference, rounding included: "
      "`data/rtt-104/wdi_owid_differences.csv`. The video uses WDI only.")
    a("")
    for d in (vd + wd + ow)[:80]:
        a(f"- {name.get(d['iso3'], d['iso3'])} {d['year']}: WDI {one_dp(d['wdi']) if d['wdi'] else '-'} / OWID "
          f"{one_dp(d['owid']) if d['owid'] else '-'} ({d['difference']}{', ' + d['amount'] if d['amount'] else ''})")
    if len(vd + wd + ow) > 80:
        a(f"- … {len(vd + wd + ow) - 80} more in the CSV")
    a(f"- OWID entities with no World Bank economy code (not compared): {', '.join(owid_only) or 'none'}.")
    a("")

    # 14 running time
    a("## 14. Running time (estimate)")
    a("")
    n = len(years)
    a(f"{n} years: at 2 s per year **{2 * n} s**, at 3 s per year **{3 * n} s** of race. With an estimated 5 s title and "
      f"8 s closing card (not designed yet): about {(2 * n + 13) // 60} min {(2 * n + 13) % 60:02d} s and "
      f"{(3 * n + 13) // 60} min {(3 * n + 13) % 60:02d} s. These are estimates, not timings.")
    a("")

    # 15 checks
    a("## 15. Checks")
    a("")
    for k in sorted(checks):
        a(f"- {k}: {'PASS' if checks[k]['pass'] else 'FAIL'} ({checks[k]['detail']})")
    a("")

    # 16 questions
    qfile = os.path.join(data_dir, "source", "report_questions.md")
    a("## 16. Questions for Luke (DEC-417: on-screen claims, scope, rights, leader-changing choices only)")
    a("")
    a(open(qfile, encoding="utf-8").read().strip() if os.path.exists(qfile) else "(none)")
    a("")
    return "\n".join(L)


def span(ys):
    """[1997, 1998, 1999, 2003] -> '1997–1999, 2003'"""
    if not ys:
        return ""
    out, start, prev = [], ys[0], ys[0]
    for y in ys[1:] + [None]:
        if y is not None and y == prev + 1:
            prev = y
            continue
        out.append(f"{start}" if start == prev else f"{start}–{prev}")
        if y is not None:
            start = prev = y
    return ", ".join(out)


def story_moments(economies, parl, elig, boards, years, one_dp, name):
    out = []
    lead = [b for b in boards if b["board"] == "top" and b["rank"] == 1]
    seq = []
    for b in lead:
        if not seq or seq[-1][0] != b["country"]:
            seq.append([b["country"], b["year"], b["year"], b["value_1dp"]])
        else:
            seq[-1][2] = b["year"]
    out.append("Leaders: " + "; ".join(f"{c} {s}–{e}" if s != e else f"{c} {s}" for c, s, e, v in seq) + ".")
    for c, label in (("RWA", "Rwanda"), ("ARE", "United Arab Emirates"), ("SAU", "Saudi Arabia")):
        p = parl.get(c, {})
        if not p:
            continue
        z = [y for y in years if y in p and Decimal(p[y]) == ZERO]
        steps, last = [], None
        for y in years:
            if y in p and one_dp(p[y]) != last:
                steps.append(f"{y} {one_dp(p[y])}%")
                last = one_dp(p[y])
        out.append(f"{label}: " + (f"0% in {span(z)}; " if z else "") + "changes: " + ", ".join(steps) + ".")
    jp = [b for b in boards if b["iso3"] == "JPN"]
    out.append("Japan on the bottom board: " + (", ".join(f"{b['year']} (rank {b['rank']}, {b['value_1dp']}%)" for b in jp
                                                       if b["board"] == "bottom") or "never") + ".")
    for thr in (50, 60):
        hit = [(y, c) for y in years for c in sorted(parl) if elig.get(c) and y in parl[c] and Decimal(parl[c][y]) >= thr]
        if hit:
            y0 = hit[0][0]
            out.append(f"First year an in-race country is at {thr}% or more: {y0} (" + ", ".join(
                f"{name[c]} {one_dp(parl[c][y0])}%" for y, c in hit if y == y0) + ").")
    rises = []
    for c, p in parl.items():
        if not elig.get(c):
            continue
        for y in years:
            if y in p and y - 1 in p:
                rises.append((Decimal(p[y]) - Decimal(p[y - 1]), y, c))
    rises.sort(key=lambda t: (-t[0], t[1], t[2]))
    out.append("Largest one-year rises (in the race): " + "; ".join(
        f"{name[c]} {y - 1}→{y} {one_dp(parl[c][y - 1])}%→{one_dp(parl[c][y])}%" for d, y, c in rises[:6]) + ".")
    zero_last = [(y, c) for y in years for c in sorted(parl) if elig.get(c) and y in parl[c] and Decimal(parl[c][y]) == ZERO]
    if zero_last:
        yl = zero_last[-1][0]
        out.append(f"Last year with an in-race country at 0%: {yl} (" + ", ".join(name[c] for y, c in zero_last if y == yl) + ").")
    return out
